### ISSUE TITLE
Use charmcraft.yaml's 'charm-libs' feature

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/juju-sdk-tutorial-k8s#64]
charmcraft.yaml [now lets you specify the required libs](https://juju.is/docs/sdk/charmcraft-yaml#heading--charm-libs), like:

```yaml
charm-libs:
    # Fetch postgres_client lib with API version 1 and latest patch:
    - lib: postgresql.postgres_client
      version: "1"
```

This can be used with `fetch-libs`, and (even more usefully) will automatically be used to update the libs if they don't match when `pack` is run (with the next release of charmcraft).

This should mean that we can remove the libs from the repo, putting in the reference in charmcraft.yaml instead (and ignoring them via gitignore), and (a) we can be clearer and more consistent on what version is used, and (b) everything will still just work when people pack. The tutorial doc should also be updated, of course. This should make it simpler to do updates (it's just changing a number and merging that through).
